name: esky
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: 2.10.3

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation:

dev_dependencies:
  build_runner:
  freezed: ^1.1.1
  flutter_lints: ^1.0.0

flutter:
